name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  xcode_13_3:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.3.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version
        run: swift --version
      - name: Build and Test
        run: swift test --enable-code-coverage
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/FlyingFoxPackageTests.xctest/Contents/MacOS/FlyingFoxPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage_report.lcov

  xcode_13_2_1:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version
        run: swift --version
      - name: Build and Test
        run: swift test

  linux:
    runs-on: ubuntu-latest
    container: swift:5.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift test
